apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-repo
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/akselleirv/tf-testing
  ref:
    branch: main